name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter  
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.0
  firebase_storage: ^11.7.6
  firebase_auth: ^4.19.6
  image_picker: ^1.1.1
  universal_html: ^2.0.9
  flutter_lints: ^4.0.0
  flutter_animate: ^4.5.0
  google_fonts: ^4.0.4




flutter:
  uses-material-design: true
