// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrq7izIUnOQ4gwdSfIj_uVZCcSNqFSwPI',
    appId: '1:1034298218519:web:f6f735140133ba5545a452',
    messagingSenderId: '1034298218519',
    projectId: 'employeetraking-e250e',
    authDomain: 'employeetraking-e250e.firebaseapp.com',
    storageBucket: 'employeetraking-e250e.appspot.com',
    measurementId: 'G-2Z46C3FSV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5PF19ldVekqhF9nADDikBw-I5cLWlX3M',
    appId: '1:1034298218519:android:07d1bb57e299f0bd45a452',
    messagingSenderId: '1034298218519',
    projectId: 'employeetraking-e250e',
    storageBucket: 'employeetraking-e250e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFR7j-dS32dqSG7cYeL_oYplbnpBtxI5I',
    appId: '1:1034298218519:ios:bdbbfa132903d09545a452',
    messagingSenderId: '1034298218519',
    projectId: 'employeetraking-e250e',
    storageBucket: 'employeetraking-e250e.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFR7j-dS32dqSG7cYeL_oYplbnpBtxI5I',
    appId: '1:1034298218519:ios:bdbbfa132903d09545a452',
    messagingSenderId: '1034298218519',
    projectId: 'employeetraking-e250e',
    storageBucket: 'employeetraking-e250e.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrq7izIUnOQ4gwdSfIj_uVZCcSNqFSwPI',
    appId: '1:1034298218519:web:89256c4b7f6ce80745a452',
    messagingSenderId: '1034298218519',
    projectId: 'employeetraking-e250e',
    authDomain: 'employeetraking-e250e.firebaseapp.com',
    storageBucket: 'employeetraking-e250e.appspot.com',
    measurementId: 'G-6CKNJC1YEY',
  );
}
